part1: part1.cpp
	g++ part1.cpp -o part1
part2: part2.cpp
	g++ part2.cpp -o part2
part3: 
	g++ part3.cpp -o part3
part4: 
	
part5: 
	

############### DON'T TOUCH BELOW ##################
run%: part%
	@./part$* || :

